### PR TITLE
Updated the Plugin to UE4.20

### PR DESCRIPTION
**Pull request by Umax1004**
I used hausfrau87's pull request as a based and then changed the macro calls for the uniform buffer and modified target and build files so that it can work with UE4.20. It runs the project and the compute shaders work.

### CODE REVIEW

**Comment by Temaran** [comment]
Oh wow, this is really cool!

Thanks :)
I hope to return to this and improve everything when I can find some time, but in the meantime this is fanntastic!

/Temaran

**Comment by freeplanet** [comment]
Thanks guys, it works well on a Mac!

I had only one issue with the shader compilation, because of: 
"OutputSurface.GetDimensions(sizeX, sizeY);" in ComputeShaderExample.usf.
The error was: "Failed to compile locally to bytecode ...use of undeclared identifier 'imageSize'
        v4.xy = imageSize( OutputSurface);"
So I had just to comment this line, and give some hard coded values to sizeX & sizeY (for the moment).

**Comment by Umax1004** [comment]
@freeplanet Sadly I don't have a mac so I can't test it :( Still will look at it if someone else found a solution.

**Comment by freeplanet** [comment]
Ok thanks @Umax1004 !
