### PR TITLE
Updated to 5.0

### PR DESCRIPTION
**Pull request by tomotaco**
Confirmed working on 5.0.2.
I hope this request might be any help.

### CODE REVIEW

**Comment by Code-Guy** [comment]
you are my lifesaver! thanks a lot :)

**Comment by redsigma** [comment]
can confirm this works on UE5.1

**Comment by MatthisL** [comment]
Not working for me on UE5.1.
Part of compile errors : 
```
0>ComputeShaderExample.cpp(29): Error C2338 : static_assert failed: 'Invalid type FVector2D of member TextureSize.'
0>ComputeShaderExample.cpp(58): Error C2653 : 'EResourceTransitionAccess': is not a class or namespace name
0>ComputeShaderExample.cpp(58): Error C2065 : 'ERWBarrier': undeclared identifier
0>ComputeShaderExample.cpp(58): Error C2653 : 'EResourceTransitionPipeline': is not a class or namespace name
0>ComputeShaderExample.cpp(58): Error C2065 : 'EGfxToCompute': undeclared identifier
0>PixelShaderExample.cpp(31): Error C2679 : binary '=': no operator found which takes a right-hand operand of type 'FVector4' (or there is no acceptable conversion)
```

**Comment by MatthisL** [comment]
For the transition call on RHICmdList :


```cpp
//RHICmdList.TransitionResource(EResourceTransitionAccess::ERWBarrier, EResourceTransitionPipeline::EGfxToCompute, ComputeShaderOutputUAV); // I have no idea to replace this line with.
ERHIAccess BarrierAccess = ERHIAccess::CopySrc | ERHIAccess::CopyDest | ERHIAccess::SRVCompute | ERHIAccess::SRVGraphics | ERHIAccess::UAVCompute | ERHIAccess::UAVGraphics;
FRHITransitionInfo TransitionInfo(ComputeShaderOutputUAV, BarrierAccess);
RHICmdList.Transition(TransitionInfo);
```

**Comment by Temaran** [comment]
Oh, completely missed this :)

I updated the entire project to 5.3 today, moving the examples to RDG instead.
